pipeline {
  agent {
    docker {
      image 'php:7.4-alpine'
    }
  }
  stages {
    stage('verify version') {
      steps {
        sh 'php --version'
      }
    }
    stage('hello') {
      steps {
        sh 'php hello.php'
      }
    }
  }
}
